import numpy
a=numpy.array([12,34,56,78])
b=numpy.array([12,87,76,54])
print(a)
print(b)
comp=(a==b)
print(comp)
if comp.all(): #all is a function fopr test all the elements
    print("all are exactly same")
else:
    print("array are diffrent")
print(numpy.sum(a)) #sumis a function use for to sum all elements of a array
print(numpy.product(a))    
print(numpy.add(a,b)) #add is a unction use for 2 or more 
power=numpy.float_power(a,b)
print(power)
print("avarage of no is")
z=numpy.average(a)
print(a)

z=numpy.mean(a)
print(z)
z=numpy.median
print(z)
s=numpy.array([12,3,4,78])
print(s)
print(s[0])
print(a[0:3])
print(a[3:])
print(a[:2])
print(a[-2])
arr=numpy.array([12,3,45,67])
print(arr)
print(arr[arr%2==1])
a=numpy.array([[1,23,4,12],[12,34,56,23],[12,34,56,78]])
print(a)
print(a.shape)  #shape is a attribute 
print("to print all rows and all colun")
print(a[:,:])
print("all rows and 2 column")
print(a[:,0:2])
print(a[:,2])
print(a[a<=40])
arr=numpy.arange(15)
print(arr)
b=arr.reshape(3,5)
print(b)
a=numpy.array([1.2,1.34,3.23,4.34])
print(a)
print(numpy.around(a))
print(numpy.floor(a))
a=numpy.array(["ankita","gudi","lucky","guddan"])
print(a)
print(numpy.char.upper(a))
print(numpy.char.capitalize(a))
print(numpy.char.title(a))

